INSERT INTO product VALUES ("CodProdus1",1050.99,"iphone description","Iphone",10);
INSERT INTO product VALUES ("CodProdus2",100.99,"mac book description","Mac Book",10);
INSERT INTO product VALUES ("CodProdus3",1020.10,"ebook reader description","Ebook reader",10);
INSERT INTO product VALUES ("CodProdus4",400.44,"Wireless keyboard description","Wireless keyboard",10);
INSERT INTO product VALUES ("CodProdus5","Wireless keyboard","Wireless keyboard description",5,243.60);
INSERT INTO product VALUES ("CodProdus6","Smart Watch","smart watch description",9,1140.45);
INSERT INTO product VALUES ("CodProdus7","Usb cable","usb cable description",15,50.55);
INSERT INTO product VALUES ("CodProdus8","Carcasa pc","carcasa pc description",20,300.99);
INSERT INTO product VALUES ("CodProdus9","Cooler","cooler description",30,210.50);
INSERT INTO product VALUES ("CodProdus10","Graphic card","graphic card description",12,1545.50);